### ISSUE TITLE
Conflicts with Apotheosis

### ISSUE THREAD

**Issue by Azzmikaelson** [Fuzss/enchantinginfuser-fabric#7]
When I open the enchanting table infuser, It doesn't show all the enchantments and once I put the item closing the menu. It won't let me open the menu again unless I break it.

**Comment by Fuzss** [comment]
This is entirely up to the Apotheosis Fabric dev, I created an issue over there.
https://github.com/Safrodev/Apotheosis-Fabric/issues/6

No clue why the set the field to null that is causing the crash, my mod won't work without the information from that field.
